name: Publish Swift Package
on: [push]
jobs:
  release-swift-package:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Find next tag
        uses: mathieudutour/github-tag-action@v6.0
        id: findNextTag
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          with_v: true
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew createSwiftPackage
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: shared/swiftpackage/EmbarkX-*.zip
          tag_name: ${{ steps.findNextTag.outputs.new_tag }}
      - name: Set XCFramework Replace URL
        id: xcframework
        run: |
          echo '::set-output name=REPLACE_URL::"url: ${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }} // XC_FRAMEWORK_URL"'
      - name: Replace url in Package.swift
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: |
            url: ".*", \/\/ XC_FRAMEWORK_URL
          replace: ${{ steps.xcframework.REPLACE_URL }}
          regex: true
      - name: Get checksum of XCFramework ZIP
        id: checksum
        run: |
          echo '::set-output name=REPLACE_CHECKSUM::"checksum: $(md5 shared/swiftpackage/EmbarkX-*.zip)" // XC_FRAMEWORK_CHECKSUM'
      - name: Replace checksum in Package.swift
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: |
            checksum: ".*", \/\/ XC_FRAMEWORK_CHECKSUM
          replace: ${{ steps.checksum.outputs.REPLACE_CHECKSUM }}
          regex: true
      - uses: EndBug/add-and-commit@v7
        with:
          add: "Package.swift"
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          with_v: true