name: Publish Swift Package
on: [push, pull_request]
jobs:
  release-swift-package:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Find next tag
        uses: anothrNick/github-tag-action@1.36.0
        id: findNextTag
        env:
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew createSwiftPackage
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: shared/swiftpackage/EmbarkX-*.zip
          tag_name: ${{ steps.findNextTag.outputs.newTag }}
      - name: Replace url in Package.swift
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'url: ".*", \/\/ XC_FRAMEWORK_URL'
          replace: "url: ${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }} // XC_FRAMEWORK_URL"
          regex: true
      - name: Get checksum of XCFramework ZIP
        id: checksum
        run: echo '::set-output name=XC_FRAMEWORK_CHECKSUM::$(md5 shared/swiftpackage/EmbarkX-*.zip)'
      - name: Replace checksum in Package.swift
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'checksum: ".*", \/\/ XC_FRAMEWORK_CHECKSUM'
          replace: "checksum: ${{ steps.checksum.outputs.XC_FRAMEWORK_CHECKSUM }} // XC_FRAMEWORK_CHECKSUM"
          regex: true
      - uses: EndBug/add-and-commit@v7
        with:
          add: "Package.swift"
