name: Run Unit-tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@2.5.0
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Run Unit-tests
        run: ./gradlew testDebugUnitTest